version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nandhu01
      POSTGRES_DB: project1
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
